name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    env: 
      DatabaseCollection: DatingAppStaging
      DatabaseConnectionString: mongodb+srv://K125_member2:asdw1357@cluster0.gnzfm1q.mongodb.net/test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
      - run: echo $DatabaseCollection
