name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read
  
env: 
  DatabaseCollection: DatingAppStaging
  DatabaseConnectionString: mongodb+srv://K125_member2:asdw1357@cluster0.gnzfm1q.mongodb.net/test

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: try to print out env
        run: echo "DBCollection:$DatabaseCollection"
      - uses: actions/checkout@v2
      - uses: education/autograding@v1

