name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read
  
env: 
  DatabaseCollection: DatingAppStaging
  DatabaseConnectionString: mongodb+srv://K125_member2:asdw1357@cluster0.gnzfm1q.mongodb.net/test

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
        env: 
          DatabaseCollection: ${{DatabaseCollection}}
          DatabaseConnectionString: ${{DatabaseConnectionString}}
      - uses: education/autograding@v1

